### PR TITLE
Fix #251: Python 2 vs Python 3: DevString with bytes

### LINKED ISSUE #251: Python 2 vs Python 3: DevString with bytes
Hi all,

I noticed an intriguing behavior of PyTango running within a Python 3 environment.

### Scenario

An old, existing C++ server to control a RS232 serial line. The server has a `DevSerReadString`
method to read chars from the serial line ; Tango output data type is `DevString`.
The equipment connected to the serial line sends binary data.

### Problem

When calling the command from a Python 2 client, everything works fine -- the returned string corresponds to the bytes sent by the equipment.
When calling the command from a Python 3 client, `None` is returned.

### Minimal example to reproduce the problem

* Server in Python 2
    
    ```python
    from tango.server import run
    from tango.server import Device
    from tango.server import attribute, command

    class BytesTest(Device):
        @command(dtype_out=str)
        def bytes_str1(self):
            return "binary_data\xee\xff"

    if __name__ == "__main__":
        run((BytesTest,))
    ```

* Python 3 client

   ```bash
    Python 3.7.1 (default, Dec 14 2018, 19:28:38) 
    [GCC 7.3.0] :: Anaconda, Inc. on linux
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import tango; dev=tango.DeviceProxy("id00/tango/test")
    >>> print(dev.bytes_str1())
    None
    >>> 
    ```

### Additional information

Of course the problem comes from bytes/unicode handling in Python. It is also probably a
bad idea to use `DevString` for this kind of data transfer, maybe `DevVarCharArray` would
have been better...

According to the PyTango documentation, `DevString` is [encoded as latin-1](https://pytango.readthedocs.io/en/v9.2.5/data_types.html), but it does not seem to be the case in reality.

    >>> s = "binary_data\xee\xff"
    >>> print(s)
    'binary_dataîÿ'
    >>> print(s.encode("latin-1"))
    b'binary_data\xee\xff'

### PR DESCRIPTION
**Pull request by tiagocoutinho**
Checked:
* attributes r/w of types *str*, *[str]*, *[[str]]*, with bytes/str, both client and server side
* commands with arg and return types *str*, *[str]* with bytes/str, both client and server side
* properties

### CODE REVIEW

File: ext/device_attribute.cpp [hunk 1]
```diff
@@ -55,12 +55,12 @@ struct python_tangocpp<Tango::DEV_STRING>
...
     static inline void to_cpp(const bopy::object & py_value, TangoScalarType & result)
     {
-        result = CORBA::string_dup(bopy::extract<TangoScalarType>(py_value));
+        result = from_str_to_char(py_value.ptr());
     }
 
     static inline bopy::object to_python(const TangoScalarType & value)
     {
-        return bopy::object(std::string(value));
+	return from_char_to_str2(value);
```
Comment (ajoubertza) [inline ext/device_attribute.cpp]: I know it didn't come in with this PR, but this is a pretty bad name for a function.  The difference between the behaviour of `from_char_to_str` and `from_char_to_str2` isn't clear at all. 
Looking at the implementation, maybe `from_char_to_python_str` and  `from_char_to_boost_str`?

Similarly, `from_str_to_char` isn't quite saying what it does.  Seems to create a C++ string from a Python string.  Maybe `from_python_str_to_char`?

File: ext/from_py.cpp [hunk 2]
```diff
@@ -11,23 +11,14 @@
...
-        ret = CORBA::string_dup(PyBytes_AsString(obj_bytes_ptr));
-        Py_DECREF(obj_bytes_ptr);
-    }
-    else
-    {
-        ret = CORBA::string_dup(PyBytes_AsString(obj_ptr));
-    }
-    return ret;
+    // DRY!
+    return from_str_to_char(obj_ptr);
```
Comment (ajoubertza) [inline ext/from_py.cpp]: Great improvement, but now we have a function that just calls another function.  Might as well just use `from_str_to_char` directly.  I only see usages of `obj_to_new_char` in this file, so should be OK to drop it.

File: ext/from_py.cpp [hunk 3]
```diff
@@ -11,23 +11,14 @@
...
 }
 
 char* obj_to_new_char(bopy::object obj)
```
Comment (ajoubertza) [inline ext/from_py.cpp]: All the usages are of the the form: `obj_to_new_char(py_obj.attr("min_alarm"))`, so I'm guessing we can probably just remove this boost object variant.

File: ext/from_py.cpp [hunk 4]
```diff
@@ -37,16 +28,7 @@ char* obj_to_new_char(bopy::object obj)
...
-    {
-        PyObject* obj_bytes_ptr = PyUnicode_AsLatin1String(obj_ptr);
-        result = PyBytes_AsString(obj_bytes_ptr);
-        Py_DECREF(obj_bytes_ptr);
-    }
-    else
-    {
-        result = PyBytes_AsString(obj_ptr);
-    }
+    from_str_to_char(obj_ptr, result);
```
Comment (ajoubertza) [inline ext/from_py.cpp]: As above, rather drop the `obj_to_string` function, as use this one elsewhere.

File: ext/from_py.cpp [hunk 5]
```diff
@@ -37,16 +28,7 @@ char* obj_to_new_char(bopy::object obj)
...
 }
 
 void obj_to_string(bopy::object obj, std::string& result)
```
Comment (ajoubertza) [inline ext/from_py.cpp]: As above, this variant seems to be unused.

File: ext/pyutils.cpp [hunk 6]
```diff
@@ -63,15 +63,37 @@ void from_str_to_char(PyObject* in, std::string& out)
...
 }
 
+char* from_str_to_char(PyObject* in)
+{
+    char* out = NULL;
+    if (PyUnicode_Check(in))
+    {
+        PyObject *bytes_in = PyUnicode_AsLatin1String(in);
+	Py_ssize_t size = PyBytes_Size(bytes_in);
+	out = new char[size+1];
```
Comment (ajoubertza) [inline ext/pyutils.cpp:94]: Will this memory get released eventually?

File: tests/test_client.py [hunk 7]
```diff
@@ -94,6 +97,13 @@
     'Status',
 ]
 
+PY3 = sys.version_info >= (3,)
+
+# char \x00 cannot be sent in a DevString. All other 1-255 chars can
+ints = tuple(range(1, 256))
+bytes_devstring = bytes(ints) if PY3 else ''.join(map(chr, ints))
+str_devstring = bytes_devstring.decode('latin-1')
```
Comment (ajoubertza) [inline tests/test_client.py]: Can't we import all these things from `test_utils.py`?  That would prevent duplication.

File: tests/test_server.py [hunk 8]
```diff
@@ -221,7 +221,7 @@ def bad_attr(self):
 # Test properties
 
 def test_device_property_no_default(typed_values, server_green_mode):
-    dtype, values = typed_values
+    dtype, values, expected_values = typed_values
```
Comment (ajoubertza) [inline tests/test_server.py]: `expected_values` isn't used in this test, but it should be.

File: tests/test_server.py [hunk 9]
```diff
@@ -245,7 +245,7 @@ def get_prop(self):
 
 
 def test_device_property_with_default_value(typed_values, server_green_mode):
-    dtype, values = typed_values
+    dtype, values, expected_values = typed_values
```
Comment (ajoubertza) [inline tests/test_server.py]: As above, `expected_values` should probably be used.

File: tests/test_server.py [hunk 10]
```diff
@@ -359,7 +359,7 @@ def PolledAttribute3(self):
 
 
 def test_mandatory_device_property(typed_values, server_green_mode):
-    dtype, values = typed_values
+    dtype, values, expected_values = typed_values
```
Comment (ajoubertza) [inline tests/test_server.py]: As above, `expected_values` should probably be used.

File: Makefile [hunk 11]
```diff
@@ -87,7 +87,7 @@ endif
 
 TANGO_CFLAGS=`pkg-config --cflags-only-other tango`
 TANGO_LIBS=`pkg-config --libs-only-l tango`
-BOOST_LIB = boost_python-py$(PY_VER_S)
+BOOST_LIB = boost_python
```
Comment (ajoubertza) [inline Makefile:92]: Why this change?   (I don't know anything about the boost library naming.)

File: Makefile [hunk 12]
```diff
@@ -145,6 +145,7 @@ LIB_NAME := _tango.so
 LIB_SYMB_NAME := $(LIB_NAME).dbg
 
 OBJS := \
+$(OBJS_DIR)/device_attribute.o \
```
Comment (ajoubertza) [inline Makefile]: Does it matter that this is now first?

**Review by ajoubertza — COMMENTED** [review]
Thanks for improvements.
I'm also wondering if the mentions of UTF-8 in https://github.com/tango-controls/pytango/blob/develop/doc/data_types.rst are still correct after this change?

**Comment by tiagocoutinho** [comment]
> Thanks for improvements.
> I'm also wondering if the mentions of UTF-8 in https://github.com/tango-controls/pytango/blob/develop/doc/data_types.rst are still correct after this change?

Yes, you are right. Every mention to UTF-8 should be changed to latin-1

File: ext/device_attribute.cpp (hunk 1 above)
Comment (tiagocoutinho) [reply ext/device_attribute.cpp]: agree with your naming.

File: ext/from_py.cpp (hunk 2 above)
Comment (tiagocoutinho) [reply ext/from_py.cpp]: agree

File: ext/from_py.cpp (hunk 5 above)
Comment (tiagocoutinho) [reply ext/from_py.cpp]: agree

File: ext/pyutils.cpp (hunk 6 above)
Comment (tiagocoutinho) [reply ext/pyutils.cpp:94]: Tango/Corba will take ownership of this memory. Maybe should put a note on the beginning of the function mentioning this

File: ext/from_py.cpp (hunk 4 above)
Comment (tiagocoutinho) [reply ext/from_py.cpp]: agree

File: tests/test_server.py (hunk 9 above)
Comment (tiagocoutinho) [reply tests/test_server.py]: Same as above

File: tests/test_server.py (hunk 10 above)
Comment (tiagocoutinho) [reply tests/test_server.py]: same as above

File: Makefile (hunk 11 above)
Comment (tiagocoutinho) [reply Makefile:92]: Sorry, the Makefile commit is a spurious commit.
This was because in my dev env I was using *conda* and the *conda* boost package does not suffix the library name with the python version.

I will undo this

File: Makefile (hunk 12 above)
Comment (tiagocoutinho) [reply Makefile]: same spurious commit

I will undo this

File: tests/test_server.py (hunk 8 above)
Comment (tiagocoutinho) [reply tests/test_server.py]: In this specific test, the expected value is always the default `values[0]`, so here I can remove it.

File: ext/from_py.cpp (hunk 3 above)
Comment (tiagocoutinho) [reply ext/from_py.cpp]: not sure I understand what you mean.
by the previous comments I was thinking to ` obj_to_new_char` would be replaced by ` from_str_to_char`. Is that is?

**Comment by tiagocoutinho** [comment]
Thanks for the revision @ajoubertza. It is much appreciated!

**Comment by tiagocoutinho** [comment]
@ajoubertza, I think I have made all the modifications according to your review.

I have spotted some problems with the database as well. I believe I managed to fix them all.
Unfortunately the C++ FileDatabase which is used in the tests does not support the extended ascii character table in properties (and neither the '\\' or the '\n' characters) so I couldn't add tests for this.

If you have time, could you check that everything is ok now? 

Thanks

File: ext/from_py.cpp (hunk 3 above)
Comment (ajoubertza) [reply ext/from_py.cpp]: Yes, that's it.

File: tests/test_async.py [hunk 13]
```diff
@@ -24,14 +24,14 @@ def identity(self, arg):
             return arg
 
     with DeviceTestContext(TestDevice) as proxy:
-        for value, expected_value in zip(values, expected_values):
+        for value in values:
             eid = proxy.command_inout_asynch('identity', value)
             result = proxy.command_inout_reply(eid, timeout=500)
-            assert_array_equal(result, expected_value)
+            assert_array_equal(result, expected(value))
```
Comment (ajoubertza) [inline tests/test_async.py:30]: This is a nice improvement.  More readable now, and don't need to do the zip.

File: tests/test_client.py (hunk 7 above)
Comment (ajoubertza) [reply tests/test_client.py]: Still some duplication here - these things are in `test_utils.py`.

**Review by ajoubertza — APPROVED** [review]
Looks good, @tiagocoutinho - thanks.  This was a difficult one!
(Sorry for delay in reviewing - I've been on vacation)
